Add theoretical bounds
decrypto-org/superblocks-paper pull request #6
Opened 2019-10-16 12:08 UTC by gtklocker

2019-10-30 11:42 UTC, gtklocker commented
@dionyziz ptal

2019-11-04 20:07 UTC, dionyziz requested changes
Add acknowledgment section at the end and mention Nikos.

2019-11-04 20:07 UTC, dionyziz commented on construction.tex
> +We obtain that $\EX[B^n] < \frac{1}{2}(\lg(n)+2+e)$. Therefore the expected savings are $\lg(n) - \EX[B^n] > \frac{1}{2}(\lg(n)-2-e)$. Solving for $n$ we obtain that $n > 111$ for savings to exist.
we obtain that $n > 111$ *is required* for savings to exist

2019-11-04 20:07 UTC, dionyziz commented on construction.tex
> +  We work using induction on $k$.
Hide induction behind a minimality argument.

2019-11-04 20:07 UTC, dionyziz commented on construction.tex
>  \end{figure*}
Since we have theoretical results below, the above observation and figure can be removed.

2019-11-04 20:07 UTC, dionyziz commented on construction.tex
> +    &= k+1 - \sum_{j=0}^k (1-2^{-j})^n < \lg(n) + 2 \\
I don't follow how we got here from the previous line.

2019-11-04 20:07 UTC, dionyziz commented on construction.tex
> +    -\sum_{i=1}^n (-1)^i {n \choose i} \frac{1}{2^{(k+1)i} - 2^{ki}} < e
Shouldn't this be \leq?

2019-11-04 20:07 UTC, dionyziz commented on construction.tex
> +    &< \sum_{i=1}^n {n \choose i} \frac{1}{2^{(k+1)i} - 2^{ki}} \\
\leq?

2019-11-04 20:07 UTC, dionyziz commented on construction.tex
> +    &< \sum_{i=0}^n {n \choose i} \frac{1}{2^{ki}(2^i-1)} \\
How did we get to i=0?

2019-11-04 20:07 UTC, dionyziz commented on construction.tex
> +    &\le (1+\frac{1}{n})^n < e \\
Not sure how we got here from the line above.

2019-11-05 11:20 UTC, gtklocker commented on construction.tex
> +    -\sum_{i=1}^n (-1)^i {n \choose i} \frac{1}{2^{(k+1)i} - 2^{ki}} < e
no, why?

2019-11-05 11:21 UTC, gtklocker commented on construction.tex
> +    &= k+1 - \sum_{j=0}^k (1-2^{-j})^n < \lg(n) + 2 \\
binomial expansion, explain more clearly in the new version

2019-11-05 11:22 UTC, gtklocker commented on construction.tex
> +    &< \sum_{i=0}^n {n \choose i} \frac{1}{2^{ki}(2^i-1)} \\
isn't the previous amount sum smaller than the sum with an extra positive number added?

2019-11-05 11:22 UTC, gtklocker commented on construction.tex
> +    &< \sum_{i=0}^n {n \choose i} \frac{1}{2^{ki}(2^i-1)} \\
we want the i=0 to do a binomial expansion afterwards

2019-11-05 11:22 UTC, gtklocker commented on construction.tex
> +    &\le (1+\frac{1}{n})^n < e \\
added explanation

2019-11-05 11:36 UTC, gtklocker commented on construction.tex
> +  We work using induction on $k$.
is this necessary? do you think it would look much better?

2019-11-06 11:51 UTC, dionyziz commented on construction.tex
> +    &< \sum_{i=0}^n {n \choose i} \frac{1}{2^{ki}(2^i-1)} \\
The denominator is 0.

2019-11-06 11:53 UTC, gtklocker commented on construction.tex
> +    &< \sum_{i=0}^n {n \choose i} \frac{1}{2^{ki}(2^i-1)} \\
Well you're not wrong

2019-11-06 11:53 UTC, gtklocker commented on construction.tex
> +    &< \sum_{i=0}^n {n \choose i} \frac{1}{2^{ki}(2^i-1)} \\
Let me see what I can do about it

2019-11-06 11:56 UTC, dionyziz commented on construction.tex
> +  We work using induction on $k$.
If we're going to keep it as forward induction, at least we should shorten:

"By induction on $k$. Clearly it holds for $k = 0$. For $k > 0$ we have:" and the derivation can follow. If you want at some point to say "From the inductive hypothesis" at the point where you do the replacement for $k$ you can add it. I don't think we need to write out the base, the hypothesis, and the step so verbosely.

2019-11-06 12:00 UTC, gtklocker commented on construction.tex
> +    &< \sum_{i=0}^n {n \choose i} \frac{1}{2^{ki}(2^i-1)} \\
@dionyziz ok have a look at the updated version, I think it should be fine now

2019-11-06 12:06 UTC, gtklocker commented on construction.tex
> +  We work using induction on $k$.
Fair, fixing it.

2019-11-06 12:10 UTC, gtklocker commented on construction.tex
> +  We work using induction on $k$.
done

2019-11-07 10:42 UTC, dionyziz approved these changes

2019-11-07 10:43 UTC, merged